version: '3'
services:
  web:
    container_name: web
    image: nginx:1.15.6
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    container_name: myapp
    build: ./docker/php
    working_dir: /var/www/html/myapp
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql:
    container_name: mysql
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: